const SUPABASE_URL='https://lmglkxzemtvxcgktiord.supabase.co';
const SUPABASE_KEY='sb_publishable_3HyNVUYXakILMKo2SK-DJw_ka7-Yx93';
const LOGO='https://raw.githubusercontent.com/sdislamtahfizhcahayaquran/CQlass/main/logo_sd.png';
const state={classes:[],period:null,token:''};
const $=s=>document.querySelector(s);
const statusBox=$('#status');
function setStatus(msg,type='info'){statusBox.textContent=msg;statusBox.dataset.type=type}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function dash(v){const s=String(v??'').trim();return s||'-'}
function rpcUrl(name){return `${SUPABASE_URL}/rest/v1/rpc/${name}`}
async function rpc(name,payload={}){const r=await fetch(rpcUrl(name),{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY,'authorization':`Bearer ${SUPABASE_KEY}`},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||j.error||`HTTP ${r.status}`);return j}
async function call(action,payload={}){if(!state.token)throw new Error('viewer_token_missing');if(action==='bootstrap')return rpc('yayasan_live_rapor_bootstrap',{p_token:state.token});if(action==='students'||action==='class_detail')return rpc('yayasan_live_rapor_students',{p_token:state.token,p_class_id:payload.class_id});if(action==='report')return rpc('yayasan_live_rapor_report',{p_token:state.token,p_class_id:payload.class_id,p_student_id:payload.student_id});throw new Error('action_not_supported')}
function initToken(){const raw=location.hash.replace(/^#/,'').trim();if(raw){const token=raw.startsWith('k=')?decodeURIComponent(raw.slice(2)):raw;if(token)sessionStorage.setItem('cq_rapor_viewer_token',token);history.replaceState(null,'',location.pathname+location.search)}state.token=sessionStorage.getItem('cq_rapor_viewer_token')||''}
function updateKpis(){const totalClasses=state.classes.length;const students=state.classes.reduce((a,c)=>a+Number(c.student_count||0),0);const complete=state.classes.reduce((a,c)=>a+Number(c.complete_count||0),0);const incomplete=state.classes.reduce((a,c)=>a+Number(c.incomplete_count||0),0);$('#kpiClasses').textContent=totalClasses;$('#kpiStudents').textContent=students;$('#kpiComplete').textContent=complete;$('#kpiIncomplete').textContent=incomplete}
function renderClasses(){const q=$('#search').value.toLowerCase(),f=$('#filter').value;const rows=state.classes.filter(c=>`${c.name} ${c.code} ${c.homeroom||''}`.toLowerCase().includes(q)).filter(c=>f==='all'||(f==='complete'&&Number(c.incomplete_count||0)===0)||(f==='incomplete'&&Number(c.incomplete_count||0)>0));$('#classRows').innerHTML=rows.map(c=>{const p=Math.max(0,Math.min(100,Number(c.progress||0)));const miss=(c.missing||[]).join(' • ');return `<tr><td><strong>${esc(c.name||c.code)}</strong><div class="muted">${esc(c.code||'')}</div></td><td>${esc(c.homeroom||'-')}</td><td><div class="progress"><b>${p}%</b><span class="progress-track"><i style="width:${p}%"></i></span></div>${miss?`<div class="muted">${esc(miss)}</div>`:''}</td><td>${Number(c.incomplete_count||0)?`<span class="badge warn">${esc(c.incomplete_count)} siswa</span>`:'<span class="badge">Lengkap</span>'}</td><td><button data-detail="${esc(c.id)}">Lihat</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">Belum ada data.</td></tr>';$('#classSelect').innerHTML='<option value="">Pilih kelas</option>'+state.classes.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.code)}</option>`).join('');document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));updateKpis()}
async function bootstrap(){initToken();if(!state.token){setStatus('Link viewer belum membawa token akses.','warn');$('#period').textContent='Akses belum aktif';renderClasses();return}try{setStatus('Memuat data rapor…');const j=await call('bootstrap');state.classes=j.classes||[];state.period={academic_year:j.academic_year,semester_no:j.semester_no};$('#period').textContent=`TA ${j.academic_year||'-'} • Semester ${j.semester_no||'-'} • PTS`;setStatus('Terhubung • data live • mode baca saja');renderClasses()}catch(e){setStatus(`Gagal memuat: ${e.message}`,'warn');renderClasses()}}
async function openDetail(id){try{setStatus('Memuat detail kelas…');const j=await call('class_detail',{class_id:id});const cls=state.classes.find(x=>x.id===id)||{};$('#detailTitle').textContent=`${cls.name||cls.code||'Kelas'} • ${cls.homeroom||'-'}`;$('#studentRows').innerHTML=(j.students||[]).map(s=>`<tr><td><strong>${esc(s.name)}</strong><div class="muted">NIS ${esc(s.nis||'-')} • NISN ${esc(s.nisn||'-')}</div></td><td>${s.status==='Selesai'?'<span class="badge">Selesai</span>':'<span class="badge warn">Belum lengkap</span>'}</td><td>${esc((s.missing||[]).join(', ')||'-')}</td><td><button data-report="${esc(id)}|${esc(s.id)}">Lihat Rapor</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada siswa.</td></tr>';document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const [c,s]=b.dataset.report.split('|');$('#detailDialog').close();showReport(c,s)});setStatus('Terhubung • data live • mode baca saja');$('#detailDialog').showModal()}catch(e){setStatus(`Gagal membuka kelas: ${e.message}`,'warn')}}
function headRows(r,title){return `<table class="rpv-template-head"><tbody><tr><td class="head-left" rowspan="5"><div class="rpv-brand"><img src="${LOGO}" alt="Logo"><div><b>SD ISLAM TAHFIZH CAHAYA QUR'AN</b><span>${esc(title)}</span></div></div></td><td><span class="hr-label">Student Name</span><span class="hr-colon">:</span><span>${esc(dash(r.student?.name))}</span></td></tr><tr><td><span class="hr-label">Student Number</span><span class="hr-colon">:</span><span>${esc(dash(r.student?.nis))}</span></td></tr><tr><td><span class="hr-label">NISN</span><span class="hr-colon">:</span><span>${esc(dash(r.student?.nisn))}</span></td></tr><tr><td><span class="hr-label">Class</span><span class="hr-colon">:</span><span>${esc(dash(r.class?.name||r.class?.code))}</span></td></tr><tr><td><span class="hr-label">Academic Year</span><span class="hr-colon">:</span><span>${esc(dash(r.academic_year))} / Semester ${esc(dash(r.semester_no))}</span></td></tr></tbody></table><div class="rpv-template-shadow"></div>`}
function tahfizhTable(t){t=t||{};const rows=[['Teacher / Halaqah',t.guru_halaqah],['Memorization Material',t.materi_hafalan],['Learning Progress',t.lp_tahfizh],['Current Achievement',t.realisasi_saat_ini],['Achievement',t.prestasi_tahfizh],['Completion',t.persentase],['Total Surah',t.jumlah_surat],['Total Verses',t.jumlah_ayat],['Total Lines',t.jumlah_baris]];return `<div class="rpv-section-plain">Tahfizh Al-Qur'an</div><table class="rpv-tahfizh"><tbody>${rows.map(x=>`<tr><td>${esc(x[0])}</td><td>:</td><td>${esc(dash(x[1]))}</td></tr>`).join('')}</tbody></table>`}
function academicTable(rows){const body=(rows||[]).flatMap(x=>(x.scores||[]).map((s,i)=>({name:x.name,tp:`TP ${i+1}`,desc:s.learning_objective,score:s.score,avg:x.average})));return `<div class="rpv-section-plain">Academic Achievement</div><table class="rpv-table rpv-academic"><thead><tr><th style="width:5%">No</th><th style="width:24%">Subject</th><th style="width:9%">TP</th><th>Learning Objective</th><th style="width:9%">Score</th></tr></thead><tbody>${body.length?body.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.tp)}</td><td>${esc(dash(x.desc))}</td><td class="center">${esc(dash(x.score))}</td></tr>`).join(''):'<tr><td colspan="5" class="center">No academic score yet.</td></tr>'}</tbody></table>`}
function attendanceTable(a){a=a||{};return `<div class="rpv-section-plain">Attendance</div><table class="rpv-table rpv-attendance"><thead><tr><th>Effective Days</th><th>Present</th><th>Sick</th><th>Excused</th><th>Unexcused</th><th>Late</th></tr></thead><tbody><tr><td>${esc(dash(a.effective_days))}</td><td>${esc(dash(a.present_count))}</td><td>${esc(dash(a.sick_count))}</td><td>${esc(dash(a.excused_count))}</td><td>${esc(dash(a.unexcused_count))}</td><td>${esc(dash(a.late_count))}</td></tr></tbody></table>`}
function extraTable(rows){return `<div class="rpv-section-plain">Extracurricular</div><table class="rpv-table rpv-exkul"><thead><tr><th style="width:6%">No</th><th>Activity</th><th style="width:15%">Activity</th><th style="width:15%">Skill</th><th style="width:15%">Competition</th></tr></thead><tbody>${(rows||[]).length?(rows||[]).map((x,i)=>`<tr><td>${i+1}</td><td>${esc(dash(x.name))}</td><td>${esc(dash(x.activity_grade))}</td><td>${esc(dash(x.skill_grade))}</td><td>${esc(dash(x.competition_grade))}</td></tr>`).join(''):'<tr><td colspan="5" class="center">-</td></tr>'}</tbody></table>`}
function pointsTable(p){p=p||{};return `<div class="rpv-section-plain">Reward & Discipline</div><table class="rpv-table rpv-score-table"><thead><tr><th>Reward Points</th><th>Discipline Points</th></tr></thead><tbody><tr><td>${esc(dash(p.reward_points))}</td><td>${esc(dash(p.discipline_points))}</td></tr></tbody></table>`}
function signatures(r){const c=r.config||{};return `<div class="rpv-date-center">${esc(dash(c.report_date_gregorian))}${c.report_date_hijri?` / ${esc(c.report_date_hijri)}`:''}</div><div class="rpv-signatures"><div><span>Homeroom Teacher</span><div class="sig-space">${c.homeroom_signature_available?'Signature available':''}</div><b>${esc(dash(r.homeroom))}</b></div><div><span>Principal</span><div class="sig-space">${c.principal_signature_available?'Signature available':''}</div><b>${esc(dash(c.principal_name))}</b></div></div>`}
function renderPts(r){const title='MID SEMESTER STUDENT REPORT';return `<div class="rpv-paper-wrap" id="rpv-preview"><section class="rpv-paper">${headRows(r,title)}${tahfizhTable(r.tahfizh)}${academicTable(r.academic)}</section><section class="rpv-paper">${headRows(r,title)}${attendanceTable(r.attendance)}${extraTable(r.extracurricular)}${pointsTable(r.points)}${signatures(r)}<div class="rpv-footer">NPSN: ${esc(dash(r.config?.npsn))} • Read only preview from CQlass</div></section></div>`}
async function showReport(classId,studentId){document.querySelector('[data-tab="rapor"]').click();$('#reportArea').innerHTML='<div class="report-loading">Memuat rapor PTS…</div>';try{const r=await call('report',{class_id:classId,student_id:studentId});$('#reportArea').innerHTML=renderPts(r);setStatus('Rapor PTS live • mode baca saja')}catch(e){$('#reportArea').innerHTML=`<div class="report-error">Gagal memuat rapor: ${esc(e.message)}</div>`;setStatus(`Gagal memuat rapor: ${e.message}`,'warn')}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#search').oninput=renderClasses;$('#filter').onchange=renderClasses;$('#refresh').onclick=bootstrap;$('#closeDialog').onclick=()=>$('#detailDialog').close();$('#classSelect').onchange=e=>$('#openClass').disabled=!e.target.value;$('#openClass').onclick=()=>{const id=$('#classSelect').value;if(id)openDetail(id)};bootstrap();