const SUPABASE_URL='https://lmglkxzemtvxcgktiord.supabase.co';
const SUPABASE_KEY='sb_publishable_3HyNVUYXakILMKo2SK-DJw_ka7-Yx93';
const state={classes:[],period:null,token:''};
const $=s=>document.querySelector(s);
const statusBox=$('#status');
function setStatus(msg,type='info'){statusBox.textContent=msg;statusBox.dataset.type=type}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function rpcUrl(name){return `${SUPABASE_URL}/rest/v1/rpc/${name}`}
async function rpc(name,payload={}){const r=await fetch(rpcUrl(name),{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY,'authorization':`Bearer ${SUPABASE_KEY}`},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||j.error||`HTTP ${r.status}`);return j}
async function call(action,payload={}){if(!state.token)throw new Error('viewer_token_missing');if(action==='bootstrap')return rpc('yayasan_live_rapor_bootstrap',{p_token:state.token});if(action==='students'||action==='class_detail')return rpc('yayasan_live_rapor_students',{p_token:state.token,p_class_id:payload.class_id});throw new Error('report_preview_not_active')}
function initToken(){const raw=location.hash.replace(/^#/,'').trim();if(raw){const token=raw.startsWith('k=')?decodeURIComponent(raw.slice(2)):raw;if(token)sessionStorage.setItem('cq_rapor_viewer_token',token);history.replaceState(null,'',location.pathname+location.search)}state.token=sessionStorage.getItem('cq_rapor_viewer_token')||''}
function updateKpis(){const totalClasses=state.classes.length;const students=state.classes.reduce((a,c)=>a+Number(c.student_count||0),0);const complete=state.classes.reduce((a,c)=>a+Number(c.complete_count||0),0);const incomplete=state.classes.reduce((a,c)=>a+Number(c.incomplete_count||0),0);$('#kpiClasses').textContent=totalClasses;$('#kpiStudents').textContent=students;$('#kpiComplete').textContent=complete;$('#kpiIncomplete').textContent=incomplete}
function renderClasses(){const q=$('#search').value.toLowerCase(),f=$('#filter').value;const rows=state.classes.filter(c=>`${c.name} ${c.code} ${c.homeroom||''}`.toLowerCase().includes(q)).filter(c=>f==='all'||(f==='complete'&&Number(c.incomplete_count||0)===0)||(f==='incomplete'&&Number(c.incomplete_count||0)>0));$('#classRows').innerHTML=rows.map(c=>{const p=Math.max(0,Math.min(100,Number(c.progress||0)));return `<tr><td><strong>${esc(c.name||c.code)}</strong><div class="muted">${esc(c.code||'')}</div></td><td>${esc(c.homeroom||'-')}</td><td><div class="progress"><b>${p}%</b><span class="progress-track"><i style="width:${p}%"></i></span></div></td><td>${Number(c.incomplete_count||0)?`<span class="badge warn">${esc(c.incomplete_count)} siswa</span>`:'<span class="badge">Lengkap</span>'}</td><td><button data-detail="${esc(c.id)}">Lihat</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">Belum ada data.</td></tr>';$('#classSelect').innerHTML='<option value="">Pilih kelas</option>'+state.classes.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.code)}</option>`).join('');document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));updateKpis()}
async function bootstrap(){initToken();if(!state.token){setStatus('Link viewer belum membawa token akses.','warn');$('#period').textContent='Akses belum aktif';renderClasses();return}try{setStatus('Memuat data rapor…');const j=await call('bootstrap');state.classes=j.classes||[];state.period={academic_year:j.academic_year,semester_no:j.semester_no};$('#period').textContent=`TA ${j.academic_year||'-'} • Semester ${j.semester_no||'-'} • PTS`;setStatus('Terhubung • data live • mode baca saja');renderClasses()}catch(e){setStatus(`Gagal memuat: ${e.message}`,'warn');renderClasses()}}
async function openDetail(id){try{setStatus('Memuat detail kelas…');const j=await call('class_detail',{class_id:id});const cls=state.classes.find(x=>x.id===id)||{};$('#detailTitle').textContent=`${cls.name||cls.code||'Kelas'} • ${cls.homeroom||'-'}`;$('#studentRows').innerHTML=(j.students||[]).map(s=>`<tr><td><strong>${esc(s.name)}</strong><div class="muted">NIS ${esc(s.nis||'-')} • NISN ${esc(s.nisn||'-')}</div></td><td>${s.status==='Selesai'?'<span class="badge">Selesai</span>':'<span class="badge warn">Belum lengkap</span>'}</td><td>${esc((s.missing||[]).join(', ')||'-')}</td><td><button data-report="${esc(id)}|${esc(s.id)}">Lihat Rapor</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada siswa.</td></tr>';document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const [c,s]=b.dataset.report.split('|');$('#detailDialog').close();showReport(c,s)});setStatus('Terhubung • data live • mode baca saja');$('#detailDialog').showModal()}catch(e){setStatus(`Gagal membuka kelas: ${e.message}`,'warn')}}
async function showReport(classId,studentId){document.querySelector('[data-tab="rapor"]').click();$('#reportArea').innerHTML='<article class="report-card"><h2>Preview rapor sedang disiapkan</h2><p class="muted">Data kelas dan status siswa sudah live. Berikutnya preview akan menggunakan sumber rapor CQlass yang sama tanpa membuka akses edit.</p></article>'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#search').oninput=renderClasses;$('#filter').onchange=renderClasses;$('#refresh').onclick=bootstrap;$('#closeDialog').onclick=()=>$('#detailDialog').close();$('#classSelect').onchange=e=>$('#openClass').disabled=!e.target.value;$('#openClass').onclick=()=>{const id=$('#classSelect').value;if(id)openDetail(id)};bootstrap();